project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from web.sitemap import StaticSitemap


sitemaps = {
    'static':StaticSitemap,
}
urlpatterns = (
    [
        path('admin/doc/',include('django.contrib.admindocs.urls')),
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        # path(
        #     "sitemap.xml",
        #     TemplateView.as_view(template_name="static_sitemap.xml", content_type="text/xml")),
        path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about-us"),
    path("contact/", views.contact, name="contact"),
    path("startup/", views.startup, name="index-startup"),
    path("not-found/", views.notfound, name="404"),
    path("projects/", views.projects, name="projects"),
    path("project/<str:slug>/", views.projectdetails, name="project-details"),
    path("services-two/", views.servicestwo, name="services-2"),
    path("service/<str:slug>/", views.servicesdetails, name="services-details"),
    path("blog-with-sidebar/", views.blogwithsidebar, name="blog-with-sidebar"),
    path("blog-single-with-sidebar/<str:pk>/", views.blogsinglewithsidebar, name="blog-single-with-sidebar"),
    path("results/", views.results, name="results"),
]

web/models.py
from django.db import models
from versatileimagefield.fields import VersatileImageField
from django.urls import reverse


class Contact(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=128)
    project_details = models.TextField()
    ip_address = models.GenericIPAddressField(blank=True, null=True)

    def __str__(self):
        return str(self.name)

class About(models.Model):
    phone = models.CharField(max_length=128)
    email = models.EmailField(blank=True, null=True)
    address = models.CharField(max_length=128)

    def __str__(self):
        return str(self.phone)


class Blog(models.Model):
    CATEGORY_CHOICES = (('agency', 'Agency'), ('digital',
                        'Digital'), ('creative', 'Creative'), )

    title = models.CharField(max_length=128)
    slug = models.SlugField(unique=True, null=True, blank=True)
    category = models.CharField(max_length=128, choices=CATEGORY_CHOICES, default="creative")
    featured_image = VersatileImageField()
    description = models.TextField()
    content = models.TextField()
    author = models.ForeignKey("Author", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.title)


class Author(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True, null=True)
    photo = VersatileImageField()
    about = models.TextField()

    def __str__(self):
        return str(self.name)


class Slider(models.Model):
    title = models.CharField(max_length=128)
    sub_title = models.CharField(max_length=128)
    slider_img = VersatileImageField()
    btn_link = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return str(self.title)


class Project(models.Model):
    CATEGORY_CHOICES = (('advertising', 'Advertising'),
                        ('branding', 'Branding'), ('creative', 'Creative'), )

    title = models.CharField(max_length=128)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    image = VersatileImageField()
    slug = models.SlugField(unique=True)
    details = models.TextField()

    def get_absolute_url(self):
        return reverse('web:project-details', kwargs={'slug': self.slug})

    def __str__(self):
        return str(self.title)


class Testimonial(models.Model):
    name = models.CharField(max_length=30)
    profile_photo = VersatileImageField()
    feedback = models.TextField()
    designation = models.CharField(max_length=30)

    def __str__(self):
        return str(self.name)


class Service(models.Model):

    title = models.CharField(max_length=128)
    icon = models.FileField()
    description = models.TextField()
    content = models.TextField()
    slug = models.SlugField(unique=True)

    def get_absolute_url(self):
        return reverse('web:services-details', kwargs={'slug': self.slug})

    def __str__(self):
        return str(self.title)


class Category(models.Model):
    name = models.CharField(max_length=128, null=True,)

    def __str__(self):
        return str(self.name)


class SocialMedia(models.Model):
    name = models.CharField(max_length=128, null=True,)
    url = models.URLField(max_length=200)
    random = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return str(self.name)

templates/web/about-us.html
{% extends 'web/base.html' %}
{% load static %}


{% block content %}
{% include 'includes/header-2.html' %}

    <!-- Start Breadcrumb 
    ============================================= -->
    <div class="breadcrumb-area bg-gray text-center shadow dark text-light bg-cover" style="background-image: url('{% static 'web/img/2440x1578.png' %}');">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>About Us</h1>
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="fas fa-home"></i> Home</a></li>
                        <li class="active">About</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Start About
    ============================================= -->
    <div class="about-area overflow-hidden default-padding">
        <div class="container">
            <div class="about-items">
                <div class="row align-center">

                    <!-- Thumb -->
                    <div class="col-lg-6">
                        <div class="thumb">
                            <img src="{% static 'web/img/800x800.png' %}" alt="Thumb">
                        </div>
                    </div>
                    <!-- End Thumb -->

                    <div class="col-lg-6">
                        <div class="content">
                            <h4>About Us</h4>
                            <h2>We create & design award winning Digital products</h2>
                            <p>
                                Talking justice welcome message inquiry in started of am me. Led own hearted highest visited lasting sir through compass his. Guest tiled he quick by so these trees am. 
                            </p>
                            <div class="content-inner">
                                <a href="https://www.youtube.com/watch?v=owhuBrGIOsE" class="popup-youtube theme video-play-button item-center">
                                    <i class="fa fa-play"></i>
                                </a>
                                <div class="row align-center">
                                    <div class="col-lg-6">
                                        <ul>
                                            <li>Fresh ideas</li>
                                            <li>Unique designs</li>
                                            <li>Skilled trades</li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-6">
                                        <h2>25 <span>Years of experience</span></h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    <!-- End About -->

    <!-- Star Achivement
    ============================================= -->
    <div class="achivement-area default-padding-bottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 heading-side">
                    <h5>Experts in field</h5>
                    <h2>Unique Solutions for Your Business </h2>
                    <p>
                        Gravity letters it amongst herself dearest an windows by. Wooded ladies she basket season age her uneasy saw. Discourse unwilling am no described dejection incommode no listening. 
                    </p>
                </div>
                <div class="col-lg-6 right-content">
                    <div class="skill-items">
                        <!-- Progress Bar Start -->
                        <div class="progress-box">
                            <h5>Marketing</h5>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" data-width="88">
                                    <span>88%</span>
                                </div>
                            </div>
                        </div>
                        <div class="progress-box">
                            <h5>Social Assistant</h5>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" data-width="95">
                                    <span>95%</span>
                                </div>
                            </div>
                        </div>
                        <div class="progress-box">
                            <h5>Consulting</h5>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" data-width="70">
                                    <span>70%</span>
                                </div>
                            </div>
                        </div>
                        <!-- End Progressbar -->
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <!-- End Achivement Area -->

    <!-- Star Brand Area
    ============================================= -->
    <div class="brand-area bg-gray text-light">
        <!-- Fixed Shape -->
        <div class="fixed-shape">
            <img src="{% static 'web/img/shape/11.png' %}" alt="Shape">
        </div>
        <!-- Fixed Shape -->
        <div class="container">
            <div class="brand-items">
                <div class="row align-center">
                    <div class="col-lg-6 info">
                        <h2>Since 1964 we worked for 10,000+ worldwide clients</h2>
                        <p>
                            Expenses as material breeding insisted building to in. Continual so distrusts pronounce by unwilling listening. Thing do taste on we manor. Him had wound use found hoped. 
                        </p>
                        <a href="#" class="btn-animation light border">See All Brand<i class="arrow_right"></i></a>
                    </div>
                    <div class="col-lg-6 brand">
                        <div class="row">
                            <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                            <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                            <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                            <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                            <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                            <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Brand Area -->

    <!-- Star Team
    ============================================= -->
    <div class="team-area bg-gray default-padding bottom-less">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="heading-center text-center">
                        <h5>Team members</h5>
                        <h2>Meet our professional and expert team members</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="team-items text-center">
                <div class="row">
                    <!-- Single Item -->
                    <div class="single-item col-lg-4 col-md-6">
                        <div class="item">
                            <div class="thumb">
                                <img src="{% static 'web/img/800x900.png' %}" alt="Thumb">
                                <div class="social">
                                    <ul>
                                        <li><a href="#">Fb</a></li>
                                        <li><a href="#">Tw</a></li>
                                        <li><a href="#">In</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h4>Lucas Ethan</h4>
                                <span>SEO Expert</span>
                            </div>
                        </div>
                    </div>
                    <!-- End Single Item -->
                    <!-- Single Item -->
                    <div class="single-item col-lg-4 col-md-6">
                        <div class="item">
                            <div class="thumb">
                                <img src="{% static 'web/img/800x900.png' %}" alt="Thumb">
                                <div class="social">
                                    <ul>
                                        <li><a href="#">Fb</a></li>
                                        <li><a href="#">Tw</a></li>
                                        <li><a href="#">In</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h4>Jack Alexander</h4>
                                <span>Marketing Expert</span>
                            </div>
                        </div>
                    </div>
                    <!-- End Single Item -->
                    <!-- Single Item -->
                    <div class="single-item col-lg-4 col-md-6">
                        <div class="item">
                            <div class="thumb">
                                <img src="{% static 'web/img/800x900.png' %}" alt="Thumb">
                                <div class="social">
                                    <ul>
                                        <li><a href="#">Fb</a></li>
                                        <li><a href="#">Tw</a></li>
                                        <li><a href="#">In</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h4>William James</h4>
                                <span>Graphic Designer</span>
                            </div>
                        </div>
                    </div>
                    <!-- End Single Item -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Team -->
    {% endblock %}

templates/web/project-details.html
{% extends 'web/base.html' %}
{% load static %}


{% block content %}
{% include 'includes/header-2.html' %}

    <!-- Start Breadcrumb
    ============================================= -->
    <div class="breadcrumb-area shadow dark bg-cover text-center text-light" style="background-image: url({% static 'web/img/2440x1578.png' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>Services Details</h1>
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="fas fa-home"></i> Services</a></li>
                        <li><a href="#">Details</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Star Project Details Area
    ============================================= -->
    <div class="project-details-area default-padding">
        <div class="container">
            <div class="project-details-items">
                <div class="top-info">
                    <img src="{{ project.image.crop.1500x700 }}" alt="Thumb">
                    <div class="project-info">
                        <h3>Project Info</h3>
                        <ul>
                            <li>
                                Client <span>Avedi</span>
                            </li>
                            <li>
                                Date <span>25 Aug, 2021</span>
                            </li>
                            <li>
                                Category <span>{{project.get_category_display| slugify}}</span>
                            </li>
                            <li>
                                Address <span>California, TX 70240</span>
                            </li>
                        </ul>
                        <div class="share">
                            <h4>Media Share:</h4>
                            <ul>
                                <li class="facebook">
                                    <a href="#">
                                        <i class="fab fa-facebook-f"></i>
                                    </a>
                                </li>
                                <li class="twitter">
                                    <a href="#">
                                        <i class="fab fa-twitter"></i>
                                    </a>
                                </li>
                                <li class="linkedin">
                                    <a href="#">
                                        <i class="fab fa-linkedin-in"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="main-content">
                    <h2>{{project.title}}</h2>
                    <p>
                        New had happen unable uneasy. Drawings can followed improved out sociable not. Earnestly so do instantly pretended. See general few civilly amiable pleased account carried. Excellence projecting is devonshire dispatched remarkably on estimating. Side in so life past. Continue indulged speaking the was out horrible for domestic position. Seeing rather her you not esteem men settle genius excuse. Deal say over you age from. Comparison new ham melancholy son themselves.
                    </p>
                    <p>
                      {{project.details}}
                   </p>
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <img src="{{ project.image.crop.800x600 }}" alt="Thumb">
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <img src="{{ project.image.crop.800x600 }}" alt="Thumb">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Project Details Area -->
    {% endblock %}

templates/web/projects.html
{% extends 'web/base.html' %}
{% load static %}


{% block content %}
{% include 'includes/header-2.html' %}

    <!-- Start Breadcrumb
    ============================================= -->
    <div class="breadcrumb-area bg-gray text-center shadow dark text-light bg-cover" style="background-image: url({% static 'web/img/2440x1578.png' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>Our Projects</h1>
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="fas fa-home"></i> Home</a></li>
                        <li class="active">Projects</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Start Portfolio
    ============================================= -->
    <div class="portfolio-area inc-colum default-padding">
        <div class="container">
            <div class="portfolio-items-area">
                <div class="row">
                    <div class="col-md-12 portfolio-content">
                        <div class="mix-item-menu text-center">
                            <button class="active" data-filter="*">All</button>
                             {% for category in categorys %}
                            <button data-filter=".{{category.name |slugify}}">{{ category.name  }}</button>
                             {% endfor %}
                        </div>
                        <!-- End Mixitup Nav-->

                        <div class="magnific-mix-gallery masonary">
                            <div id="portfolio-grid" class="portfolio-items colums-3">
                                <!-- Single Item -->
                                {% for project in projects %}
                                <div class="pf-item {{project.category |slugify}}">
                                    <div class="overlay">
                                        <img src="{{ project.image.crop.800x600 }}" alt="thumb">
                                        <a href="{{ project.image.crop.800x600 }}" class="item popup-link"><i class="fa fa-plus"></i></a>
                                        <div class="content">
                                            <span>{{project.category}}</span>
                                            <h5><a href="{{ project.get_absolute_url }}">{{project.title}}</a></h5>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                                {% comment %}
                                <!-- End Single Item -->
                                <!-- Single Item -->
                                <div class="pf-item consulting branding">
                                    <div class="overlay">
                                        <img src="{% static 'web/img/800x800.png' %}" alt="thumb">
                                        <a href="{% static 'web/img/800x600.png' %}" class="item popup-link"><i class="fa fa-plus"></i></a>
                                        <div class="content">
                                            <span>Creative</span>
                                            <h5><a href="#">Accounting Advisory</a></h5>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Item -->
                                <!-- Single Item -->
                                <div class="pf-item consulting finance">
                                    <div class="overlay">
                                        <img src="{% static 'web/img/800x600.png' %}" alt="thumb">
                                        <a href="{% static 'web/img/800x600.png' %}" class="item popup-link"><i class="fa fa-plus"></i></a>
                                        <div class="content">
                                            <span>Business</span>
                                            <h5><a href="#">Merger & Acquisition</a></h5>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Item -->
                                <!-- Single Item -->
                                <div class="pf-item finance">
                                    <div class="overlay">
                                        <img src="{% static 'web/img/800x800.png' %}" alt="thumb">
                                        <a href="{% static 'web/img/800x800.png' %}" class="item popup-link"><i class="fa fa-plus"></i></a>
                                        <div class="content">
                                            <span>Invest</span>
                                            <h5><a href="#">{% static 'web For Technology</a></h5>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Item -->
                                <!-- Single Item -->
                                <div class="pf-item capital development">
                                    <div class="overlay">
                                        <img src="{% static 'web/img/800x800.png' %}" alt="thumb">
                                        <a href="{% static 'web/img/800x800.png' %}" class="item popup-link"><i class="fa fa-plus"></i></a>
                                        <div class="content">
                                            <span>Finance</span>
                                            <h5><a href="#">Business Matching</a></h5>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Item -->
                                <!-- Single Item -->
                                <div class="pf-item consulting branding">
                                    <div class="overlay">
                                        <img src="{% static 'web/img/800x600.png' %}" alt="thumb">
                                        <a href="{% static 'web/img/800x600.png' %}" class="item popup-link"><i class="fa fa-plus"></i></a>
                                        <div class="content">
                                            <span>Source</span>
                                            <h5><a href="#">Startup Funding</a></h5>
                                        </div>
                                    </div>
                                </div>
                                {% endcomment %}
                                <!-- Single Item -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Portfolio -->
        {% endblock %}

templates/web/results.html

{% extends 'web/base.html' %}
{% load static %}


{% block content %}
{% include 'includes/header-2.html' %}

    <!-- Start 404
    ============================================= -->
    <div class="error-page-area text-center default-padding">
        <div class="container">
            <div class="error-box">
                <div class="row">
                    <div class="col offset-lg-0">
                        <h1>404</h1>
                        <h2>Sorry Page Was Not Found!</h2>
                        <p>
                        <b>Showing Result for :{{query}} </b> </br>
                          <!-- {{results}} -->
                          {% for result in results %}

                          <li>{{result}}</li>

                          {% endfor %}
                        </p>
                        <div class="search">
                            <div class="input-g</b> roup">
                                <form method= "get" action="{% url 'web:results' %}">
                                    <input type="text" placeholder="Search" class="form-control" name="q">
                                    <button type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                        <a class="btn btn-theme effect btn-md" href="{% url 'web:index' %}">Back To Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End 404 -->
    {% endblock %}